### ISSUE TITLE
ModuleNotFoundError: No module named 'model_net'

### ISSUE THREAD

**Issue by minutes1999** [ruijiang81/CST#1]
```
ModuleNotFoundError: No module named 'model_net'
```
hello! i just read ur CST paper and there is a track when i run Example: toy.
when i run <code>toy.ipynb</code>in jupyter notebook, i can't found <code>model_net</code>, and there isn't model_net.py in CST.main.
i think model_net is a <code>.py</code> file by yourself like <code>'utils_crm,py'</code>.
thank u.

**Comment by ruijiang81** [comment]
Hi, 

The issue should be fixed now! Thanks!
